CREATE TABLE CUSTOMER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    mail VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    make VARCHAR(20) NOT NULL,
    model VARCHAR(30) NOT NULL,
    fuel_type VARCHAR(10) NOT NULL,
    prod_year INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    customer_id BIGINT NOT NULL
);

ALTER TABLE VEHICLE
    ADD CONSTRAINT vehicle_customer_fk
    FOREIGN KEY (customer_id) REFERENCES customer(id)
