CREATE TABLE VEHICLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    make VARCHAR(20) NOT NULL,
    model VARCHAR(30) NOT NULL,
    fuel_type VARCHAR(10) NOT NULL,
    prod_year INTEGER NOT NULL,
    price NUMERIC NOT NULL
);